checks:
  php: true

filter:
  excluded_paths:
    - 'tests/'

build:
  environment:
    # Languages
    php:
      version: "7.4"

  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=build/phpunit.clover'
        coverage:
            file: 'build/phpunit.clover'
            format: 'clover'
      - php-scrutinizer-run
