language: php

php:
  - 7.4

matrix:
  include:
    - php: nightly
      env: FORCE_LATEST=1
    - php: 7.4
      env: PREFER_LOWEST=1
    - php: 7.4
      env: CSFIXER=1
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer
    - $HOME/.cache/opcache

install:
  - phpenv config-rm xdebug.ini || true;
  - composer validate --strict
  - |
    if [ "$PREFER_LOWEST" = "1" ]; then
      composer update --prefer-lowest;
    elif [ "$FORCE_LATEST" = "1" ]; then
      composer update --ignore-platform-reqs;
    else
      composer update;
    fi;

script:
  - |
    if [ "$CSFIXER" = "1" ]; then
      vendor/bin/php-cs-fixer fix --verbose --dry-run --diff --diff-format=udiff --allow-risky=yes;
    fi;
  - php vendor/bin/phpunit;
