group: travis_latest
language: php
sudo: false

matrix:
  include:
    - php: 5.3
      env: lowest=1
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
    - php: 7.2
      env: code_coverage=1
    - php: 7.3


cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer
    - $HOME/.cache/opcache

install:
  - phpenv config-rm xdebug.ini || true;

  - |
    if [ "$lowest" = "1" ]; then
      composer update --prefer-lowest --prefer-stable;
    else
      composer update;
    fi;

script:
  - |
    if [ "$code_coverage" = "1" ]; then
      phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover tests;
    else
      php vendor/bin/phpunit;
    fi;

after_script:
  - |
    if [ "$code_coverage" = "1" ]; then
      wget https://scrutinizer-ci.com/ocular.phar;
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi;
